custom:
  basic: 
    list: am9zZTphbGVqYW5kcm8=,cm9iZXJ0bzpjb3J0ZXM=,cGVkcm86cmFtaXJleg==,Y2FybWVuOm1hZ2FsbGFuZXM=,am9yZ2U6c2FsaW5hcw==,ZmVybmFuZG86Y29ydGVz
    
spring:
  activemq:
    broker-url: tcp://localhost:61616
    in-memory: false
    pool:
      enabled: false
 